### ISSUE TITLE
don't use 5080 for hep

### ISSUE THREAD

**Issue by gmaruzz** [VoicenterTeam/openimss#7]
5080 is used by external profile by freeswitch, and is a deeply ingrained setting...

I would suggest like 9060 for hep...

https://github.com/VoicenterTeam/openimss/commit/f2f43e3470d6a9f017dfced451a705d2796f9ae0

**Comment by gmaruzz** [comment]
or other ports of your choices

let's keep 5050-5090 for all sorts of sip traffic...

**Comment by lmangani** [comment]
What was using 5080? it's not part of any of our standard configs. All of our ports are in the 906x range.

**Comment by gmaruzz** [comment]
yep, was one of the opensips using 5080
fixed :)
